### ISSUE TITLE
httptreemux is incompatible with httptest.ResponseRecorder testing style

### ISSUE THREAD

**Issue by StephanDollberg** [dimfeld/httptreemux#10]
Running the following snippet gives a panic:

``` go
package main

import (
	"net/http"
	"net/http/httptest"

	"github.com/dimfeld/httptreemux"
)

func main() {
	req, _ := http.NewRequest("GET", "http://localhost/", nil)

	rtr := httptreemux.New()
	rtr.GET("/", func(_ http.ResponseWriter, _ *http.Request, _ map[string]string) {})

	respRec := httptest.NewRecorder()
	rtr.ServeHTTP(respRec, req)
}
```

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc2080680c0, 0x567f68, 0xc20801e0c0, 0xc208050b60)
	/.../github.com/dimfeld/httptreemux/router.go:170 +0x6ff
main.main()
	/.../test.go:21 +0x3ee
exit status 2
```

The reason is that httptreemux uses [request.RequestURI](https://github.com/dimfeld/httptreemux/blob/master/router.go#L166) which is not set for "client" requests.

**Comment by dimfeld** [comment]
I'm using the newRequest function at https://github.com/dimfeld/httptreemux/blob/master/router_test.go#L20 in my internal tests to set up RequestURI appropriately. Does this work for you?

**Comment by StephanDollberg** [comment]
Yeah, that would certainly work. Still it's kinda ugly I guess.

However, if you are aware of this then we can close this issue.

**Comment by dimfeld** [comment]
I suppose another option would be to change the relevant code like so:

    path := r.RequestURI
    if path != "" {
  	   rawQueryLen := len(r.URL.RawQuery)
	   pathLen := len(path)
	   if rawQueryLen != 0 || path[pathLen-1] == '?' {
	  	   // Remove any query string and the ?.
		   path = path[:pathLen-rawQueryLen-1]
		   pathLen = len(path)
	   }
    } else {
         path = r.URL
    }


I'll give it a try some time this week to make sure it actually works, but if you want to try it out, please let me know if it works well :)

**Comment by dimfeld** [comment]
The commit just now should make it work with http.NewRequest. Some of the tests use both the RequestURI method and http.NewRequest, but let me know if you're seeing any issues.

**Comment by StephanDollberg** [comment]
Yeah, thanks. That fixes my snippet.
