### ISSUE TITLE
RedirectTrailingSlash strips away query string

### ISSUE THREAD

**Issue by jrbarron** [dimfeld/httptreemux#15]
I'm not sure if this is a bug or intended behavior, but it seems that when treemux does a redirect based on an extra (or missing) trailing slash, the url that it passes to http.Redirect does not include the original query string parameters.

For example if I have a path called `/api/v1/objects/` then `/api/v1/objects?limit=10` gets redirected to `/api/v1/objects/` and the query string is lost.

**Comment by dimfeld** [comment]
Definitely not intended. I'm spending most of today flying but will get this fixed ASAP. Thanks for reporting this!

**Comment by dimfeld** [comment]
Turned out to be pretty simple. Just let me know if you're still seeing any issues. Thanks again!
