### ISSUE TITLE
Usage with negroni and route groups

### ISSUE THREAD

**Issue by codingrogue** [dimfeld/httptreemux#16]
Hey, thanks for the awesome router!

I struggling with creating two different groups of routes with group-specific middleware. Currently I'm using negroni as a middleware helper and what I want to achieve is for example to have:
```go
/users
/events
...
```
and the rest of my REST api to be protected by an API-Key HTTP Header middleware and:
```go
/web/doThis
/web/doThat
```
to be protected by a second API-Key HTTP Header middleware.

Currently I came up with the following code (based on the proposal in the negroni documentation https://github.com/codegangsta/negroni#route-specific-middleware) but it doesn't work because httptreemux is not accepting negroni.New() as a handler.

```go
mux := httptreemux.New()
webmux := httptreemux.New()

n := negroni.Classic()
n.Use(gzip.Gzip(gzip.DefaultCompression))
n.Use(negroni.HandlerFunc(handler.ApiKey))

api.NewApi(mux, webmux).Init() // where routes get defined

// based on negroni documentation
mux.Handle("GET", "/web", negroni.New(      // not even sure if GET makes sense for all
	negroni.HandlerFunc(handler.ApiKeyWeb),
	negroni.Wrap(webmux),
))

n.UseHandler(mux)
n.Run(":8080")
```
Can you think of a way to make this work out? You can tell that I'm pretty new to middlewares *gg*

Any help, or tip or direction is very appreciated :)

regards

**Comment by dimfeld** [comment]
I'm not really familiar with Negroni, but if I understand the link you supplied correctly, it looks like `negroni.New` is returning a function designed for use with the standard `net/http` router, which will have the following prototype: `func(w http.ResponseWriter, req *http.Request)`. Handlers for `httptreemux` add a third parameter, a `map[string]string` which contains any matched wildcard arguments, hence the problem.

You should just need to create a simple wrapper function that takes a negroni handler as an argument and returns a handler compatible with httptreemux. I think something like this should work:

```
func wrapHandler(h http.Handler) httptreemux.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
        h(w, r);
    }
}

// And then just wrap all your handlers in calls to that function
mux.Handle("GET", "/web", wrapHandler(negroni.New(      // not even sure if GET makes sense for all
    negroni.HandlerFunc(handler.ApiKeyWeb),
    negroni.Wrap(webmux),
)))
```

I didn't run this through the compiler so it may have a syntax error or two but hopefully that gives you an idea of what to do.

**Comment by dimfeld** [comment]
Also, if I understand what you're trying to do correctly you'll want to use `"/web/*path"` as the URL there. Unlike the default Go router, `httptreemux` won't match on path prefixes unless you explicitly tell it to. The `*path` acts as a wildcard that will match the rest of the given URL and store it in a key named `path` in the map passed to the handler (which the wrapper function ignores, in this case).

**Comment by codingrogue** [comment]
Thanks for your quick response! I tried to wrap my head around it a little bit and your solution nearly works. Wrapping my handlers works very well but I'm having problems defining sub routes that have other verbs than GET because of this line (also see my comment):
```go
// not even sure if GET makes sense for all future sub routes
mux.Handle("GET", "/web", wrapHandler(negroni.New(
```
I tried to define 2 sub routes like so:
```go
// Web
a.webmux.GET("/web/test", func(res http.ResponseWriter,
	req *http.Request, _ map[string]string) {
	util.SendOK(res)
})
a.webmux.POST("/web/text", func(res http.ResponseWriter,
	req *http.Request, _ map[string]string) {
	util.SendBadRequest(res)
})
```
But the POST variant does not work (method not allowed response). I'm afraid thats because of the wrapper route being GET but I'm not sure :/

**Comment by dimfeld** [comment]
I think you’re right. You probably do need to have a `mux.Handle(“POST”, “/web/*path”, …)` in there as well. I think you can reuse the same handler for both GET and POST here, assuming that you want the same middleware to apply to both methods.




Also looks like you wrote `/web/text` instead of `/web/test`, which will be important later.

**Comment by codingrogue** [comment]
It works! Thank you very much! 

Besides, if I use it for all verbs like you suggested, what exactly happens internally? Does httptreemux know and match the same verbs and register one route or does it map all routes although only one can work with the wrapper verb?

**Comment by dimfeld** [comment]
Cool, glad I could help!

Yes, it reuses the same node in the routing tree when you add additional handlers for POST or other methods at the same path. Each node in the tree has a member called `leafHandler map[string]HandlerFunc`, so if you add a handler for another method to an already-existing route, it just adds a new entry to that map for the method.

**Comment by codingrogue** [comment]
Well that rocks sir! Again thank you so much. :)
