### ISSUE TITLE
Can't set global OPTIONS handler

### ISSUE THREAD

**Issue by derekperkins** [dimfeld/httptreemux#17]
I tried creating a global `OPTIONS` handler (simplified below) that would match any path, but everything still returned a 405. I think the issue is that all the `OPTIONS` requests matched paths but no methods, and after the path matched, it didn't fall back to my wildcard. I don't want to manually add `OPTIONS` for every single path, and the mux panics if I wrap the `Handle` function because there are multiple registrations for the same path. Any suggestions?

```
mux.Handle("OPTIONS", "/*path", func(w http.ResponseWriter, r *http.Request, pathParams map[string]string) {
	w.Header().Set("Access-Control-Allow-Credentials", "true")
	w.Header().Set("Access-Control-Allow-Origin", r.Header.Get("Origin"))
	w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, PATCH, DELETE")
	w.Header().Set("Access-Control-Allow-Headers", "Accept, Authorization, Content-Type, Accept-Encoding")
	w.Header().Set("Access-Control-Max-Age", "600")
	w.WriteHeader(204)
})
```

**Comment by dimfeld** [comment]
Closed by #20
