### ISSUE TITLE
Method Not Allowed returned when it should not be.

### ISSUE THREAD

**Issue by raphael** [dimfeld/httptreemux#27]
Consider the following code:
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/dimfeld/httptreemux"
)

func main() {
	router := httptreemux.New()
	router.OPTIONS("/*cors", handler)
	router.GET("/foo/:id", handler)
	log.Fatal(http.ListenAndServe(":8080", router))
}

func handler(w http.ResponseWriter, r *http.Request, params map[string]string) {
	w.Write([]byte(fmt.Sprintf("%s OK", r.Method)))
}
```
Running the corresponding application and making requests to it produces:
```
$ http localhost:8080/foo/2
HTTP/1.1 200 OK
Content-Length: 6
Content-Type: text/plain; charset=utf-8
Date: Mon, 14 Mar 2016 03:55:48 GMT

GET OK
```
Correct

```
$ http options localhost:8080/foo
HTTP/1.1 200 OK
Content-Length: 10
Content-Type: text/plain; charset=utf-8
Date: Mon, 14 Mar 2016 03:55:57 GMT

OPTIONS OK 
```
Correct

```
$ http options localhost:8080/foo/2
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Mon, 14 Mar 2016 03:55:54 GMT
```
Incorrect

**Comment by derekperkins** [comment]
I think #20 should help you solve your issue

**Comment by dimfeld** [comment]
Yeah, this is expected since the mux doesn't keep separate trees for each HTTP method, so if it matches on a path but that path doesn't have a handler for the associated method, it'll return Method Not Allowed.

OPTIONS is an exception to this generally desired behavior though, so #20 which Derek pointed out (and wrote, thanks again!) should help you here.

**Comment by raphael** [comment]
#20 does not work for me because I need to be able to specify different CORS policies for different (CORS) resources. So I need to be able to define different handlers for `OPTIONS /foo/*cors` `OPTIONS /bar/baz/*cors` etc. It seems I'm out of luck then...

**Comment by dimfeld** [comment]
I see... I'll give this some thought. Can't promise anything in the short term though so you may find your needs better met with some other router. Fortunately there are a lot of alternatives, so hopefully you can find one that meets all your needs :)

**Comment by raphael** [comment]
Thanks for thinking about it :) I'm taking a different approach for now that allows me to stick with httptreemux but it seems like something people are bound to run against. In general I would be willing to pay some run-time efficiency to gain the ability for `*foo` wildcards to define "defaults" when more precise routes don't match. Seems like a powerful and useful capability.

**Comment by dimfeld** [comment]
I'm thinking that the way to handle this is to treat a "method not allowed" match as a non-match, but set some flag indicating that this happened, and then continue searching the tree. I'll have to think about this a bit more but it should allow the behavior you're looking for with no performance effect on the existing supported cases.

**Comment by raphael** [comment]
Yes that sounds perfect, only pay a hit if you fallback to a default / generic route.

**Comment by dimfeld** [comment]
This should work for your case. See `fallthrough_test.go`. Let me know if you encounter any problems.

**Comment by raphael** [comment]
Awesome! this is perfect.
