### ISSUE TITLE
Allow `*` in paths

### ISSUE THREAD

**Issue by raphael** [dimfeld/httptreemux#29]
In my API I need to define paths with `*` in them. I haven't seen a way to escape the wildcard character - maybe I missed it?

**Comment by dimfeld** [comment]
No, this isn't currently supported. It should be pretty easy to add though. I'll take a look soon or will be glad to take a PR as well.

**Comment by raphael** [comment]
Awesome! How would you see there escaping being done? `\`prefix? I can take a stab at it.

**Comment by dimfeld** [comment]
Yeah that's my thought. I just had a couple hour plane ride and took advantage of the time to implement it. Will post it up later today :)

**Comment by raphael** [comment]
Great! looking forward to it.

**Comment by dimfeld** [comment]
Ok, so if you put a `*` or `:` at the beginning of a path segment, it must be backslash escaped, like so `router.GET("\\*asteriskpath", handler)`. The backslash should not be included if it occurs anywhere else in the path, e.g. `router.GET("aaa*bbb", handler)` as it only checks at the beginning. I'm not 100% happy with that but it makes the logic much simpler. Hope that helps!
