### ISSUE TITLE
Is it possible to specify a list of headers which is going to be sent with each route?

### ISSUE THREAD

**Issue by salvador-dali** [dimfeld/httptreemux#31]
Currently in each route I have to write the following `w.Header().Set("Content-Type", "application/javascript")` at the beginning of every route. Is there a way to say: 'send this header before on each routes'?

P.S. thank you very much for excellent package.

**Comment by dimfeld** [comment]
That's a bit outside of the scope of this package, but it's pretty easy to do by creating a small function to that will take a handler function as an argument and wrap the handler inside another function that writes the header and then calls the handler.  Two ways of doing this are below:

```
func wrapHeader(handler httptreemux.HandlerFunc) httptreemux.HandlerFunc {
  return func(w http.ResponseWriter, r *http.Request, params map[string]string) {
    w.Header().Set("Content-Type", "application/javascript")
    handler(w, r, params)
   }
}

router.GET("/abc", wrapHeader(abcHandler))
```

```
router := httptreemux.New()
getWithHeader := func(path string, handler httptreemux.HandlerFunc) {
    wrappedHandler := func(w http.ResponseWriter, r *http.Request, params map[string]string) {
         w.Header().Set("Content-Type", "application/javascript")
         handler(w, r, params)
    }

   router.GET(path, handler)
}

getWithHeader("/abc", abcHandler)
```

I haven't actually compiled these so there may be a bug or two, but hopefully this gives you the right idea.

**Comment by salvador-dali** [comment]
I was aware of how to do this (still thank you for help). I thought that something like 'send all headers' already exist after seeing this `api := router.NewGroup("/api/v1")`, which is also can be achieved with a small function.

After looking through the package and not finding anything, I decided to ask you. Thank you very much for a reply.
