### ISSUE TITLE
Support for http.Handler?

### ISSUE THREAD

**Issue by ARolek** [dimfeld/httptreemux#34]
Any plans to support http.Handler alongside http.HandlerFunc?

**Comment by dimfeld** [comment]
Check out the recently merged #33.

**Comment by ARolek** [comment]
@dimfeld I noticed support for `http.HandlerFunc` which is nice when working with a function, but I'm looking to leverage the `http.Handler` interface similar to [httprouter's implementation](https://godoc.org/github.com/julienschmidt/httprouter#Router.Handler). This allows for defining structs that adhere to the interface, for example:

```go
type HandleFoo struct{
  Foo string
}

func (req HandleFoo) ServeHTTP(w http.ResponseWriter, r *http.Request) {
  // do stuff
}
```

**Comment by dimfeld** [comment]
Ah, I see. I hadn't thought about doing this, but it seems like it should be pretty easy to do with a method similar to the `http.HandlerFunc` support. I can probably get it in later this week or would also be glad to take a PR.
