### ISSUE TITLE
Feature request: Add .WithContext() option

### ISSUE THREAD

**Issue by flimzy** [dimfeld/httptreemux#36]
In addition to the new `group.UsingContext()`, I would like to see a `group.WithContext()`, that can be passed an existing context.

This is useful when passing in a general server `context.Context` object.

Example:

    func main() {
       ctx := context.WithValue(context.Background(), "somekey", "somevalue")
       router := httptreemux.New()
       ctxGroup := router.WithContext(ctx)
       ctxGroup.GET(....)

**Comment by dimfeld** [comment]
Seems like a good idea. I'm not sure if I'll have time to work on this in the next few weeks, but will be glad to look over a PR.

**Comment by dimfeld** [comment]
I just added a simple feature that isn't exactly what you requested here, but may help. In the `DefaultContext` branch the `TreeMux` now has a `DefaultContext context.Context` member. If you set this then every `http.Request` will use that context.

I still favor a more full-fledged solution, but hopefully this will satisfy your intended use case for now. I still need to test it against Go 1.6 to make sure I didn't screw anything up there, but will merge to master once I do that.

**Comment by flimzy** [comment]
Awesome! Thanks!
