### ISSUE TITLE
Dependency on dimfeld/httppath

### ISSUE THREAD

**Issue by bastiankoetsier** [dimfeld/httptreemux#39]
When tinkering with your router, I found that it depends on `github.com/dimfeld/httppath`which is not declared. Do you want a PR for including this dependency directly in the router(because it is only one func) or just one for adding this to the readme ? 

Thanks.

**Comment by dimfeld** [comment]
Yeah, just adding the function directly to this package is fine with me. I've been meaning to do that for a while, and just never got around to it.

**Comment by bastiankoetsier** [comment]
Cool! I will make a PR for it.
