### ISSUE TITLE
Setting Content-Type header to application/json is not being set in the response

### ISSUE THREAD

**Issue by RPiAwesomeness** [dimfeld/httptreemux#47]
Here's an example:

```golang
package main

import (
        mux "github.com/dimfeld/httptreemux"
        "encoding/json"
        "net/http"
)

func main() {
        router := mux.New()
        router.GET("/", func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
                response, _ := json.Marshal([]string{"foo", "bar"})
                w.WriteHeader(http.StatusOK)
                w.Header().Set("Content-Type", "application/json")
                w.Write(response)
        })
        http.ListenAndServe(":8000", router)
}
```

It would be expected that the `Content-Type` header would be set to `application/json` in the response to a request to `localhost:8000/`. However, it's not, it's simply set to `text/plain`. 

Is this expected behavior and how can I override httpremux?

**Comment by dimfeld** [comment]
This is unrelated to httptreemux, and you'll see the same behavior with any router including the one in the standard library. 

Go's `ResponseWriter` requires that you set all headers before calling `WriteHeader`. Try just moving the line that sets `Content-Type` above the `WriteHeader` line and you should be good.

**Comment by RPiAwesomeness** [comment]
Interesting. That solved it though! Thanks for the help!

**Comment by jcbritobr** [comment]
Also works for me. Thanks by the explanation.
