### ISSUE TITLE
Host Header Match

### ISSUE THREAD

**Issue by italolelis** [dimfeld/httptreemux#49]
Hello,

Thank you for this amazing library. I would like to ask if it would be possible to have something like this:

The router would have a route like this:
```
Route1:
   uri: /hello
   method: GET
   host: foo.bar
```

This request wouldn't match
```
$ curl -X GET -H example.com http://localhost/hello

/hello
Host: example.com

404 Not Found
```

This request would match
```
$ curl -X GET -H foo.bar http://localhost/hello

/hello
Host: foo.bar

200 OK
```

I can try to help implement it if it doesn't exist yet, but I would probably need some help on where to touch to do that.

Thank you again!

**Comment by dimfeld** [comment]
This is a bit outside the scope of this library and I'm hesistant to add the additional complexity for per-route host matching. But it can be implemented pretty easily with a mux for each domain, and then a small layer in front to look at the host header and figure out which one to use. Check out this blog post which does something very similar: http://codepodu.com/subdomains-with-golang/

**Comment by italolelis** [comment]
Ah cool, I can try to do that.
I have this project that is using your library https://github.com/hellofresh/janus
And I kind of already have something like you mentioned https://github.com/hellofresh/janus/blob/master/pkg/middleware/host_matcher.go

My only problem is that currently on the routes I can't have two identical URIs (which makes sense on the current scope of the library). I'll try to figure something out 😄 

Thank you for your help.
