### ISSUE TITLE
rework ParamsContextKey

### ISSUE THREAD

**Issue by bontibon** [dimfeld/httptreemux#50]
To prevent external collisions of the params context value, the following changes should be made:

1. add a new unexported type
2. define an unexported const value of the above type
3. use that const value as the params context key

This pattern is explained on the Go blog: https://blog.golang.org/context#TOC_3.2.

**Comment by dimfeld** [comment]
Thanks!

**Comment by zabawaba99** [comment]
How would you suggest testing a handlers that used this exported key?

i.e

```go
func TestMyHandler(t *testing.T) {
	req, err := http.NewRequest("GET", "/foo", strings.NewReader("something"))
	require.NoError(t, err, "Failed to create http request")
	req = req.WithContext(context.WithValue(req.Context(), httptreemux.ParamsContextKey, map[string]string{
		"foo": "bar",
	}))
	w := httptest.NewRecorder()
	myHandler(w, req)
	assert.Equal(t, 200, w.Code)
}
```

**Comment by bontibon** [comment]
@zabawaba99  Why isn't that test being run against the router's ServeHTTP method?

**Comment by dimfeld** [comment]
I just added a function called AddParamsToContext, that you can use to apply your own params map to a context in your unit tests. Hope this helps!
