### ISSUE TITLE
Export lookup

### ISSUE THREAD

**Issue by azihsoyn** [dimfeld/httptreemux#52]
I'm using [goa](https://github.com/goadesign/goa) using httptreemux and [kami](https://github.com/guregu/kami) in same project (under refactoring).

So, I want to handle request which router can handle.

like this
```
// goa.Router is httptreemux
if goa.Router.Lookup(w, r) {
    goa.Router.ServeHTTP(w, r)
    return
}
kami.ServeHTTP(w, r)
```

https://github.com/dimfeld/httptreemux/blob/master/router.go#L90

Thanks.

**Comment by dimfeld** [comment]
Here's the new API. This allows you to pass the lookup result into the router for serving, without needing to look it up again. I also changed the internal lookup function to not send a response in an error case; this is now handled by the serve function.

```
if result, found := router.Lookup(w, r); found {
  router.ServeLookupResult(w, r, result)
}
```

**Comment by azihsoyn** [comment]
Thank you so much!!
