### ISSUE TITLE
URL is escaped twice on trailing slash redirect

### ISSUE THREAD

**Issue by Backfighter** [dimfeld/httptreemux#59]
The following test uncovers an issue with the current implementation of httptreemux:
```golang
func TestRedirectEscapedPath(t *testing.T) {
	router := NewContextMux()

	testHandler := func(w http.ResponseWriter, r *http.Request) {}

	router.GET("/:escaped/", testHandler)

	w := httptest.NewRecorder()
	u, err := url.Parse("/Test P@th")
	if err != nil {
		t.Error(err)
		return
	}
	r := httptest.NewRequest(http.MethodGet, u.String(), nil)

	router.ServeHTTP(w, r)

	path, err := w.Result().Location()
	if err != nil {
		t.Error(err)
		return
	}
	expected := "/Test%20P@th/"
	if path.String() != expected {
		t.Errorf("Given path wasn't escaped correctly.\n" +
			"Expected: %q\nBut got: %q", expected, path.String())
	}
}
```

This is caused since in [lookup](https://github.com/dimfeld/httptreemux/blob/8cc36ee10f84b82d0742ffcab770815c7d3f9ad7/router.go#L109), path is used for redirects but it still contains escaped characters. Then in [redirect](https://github.com/dimfeld/httptreemux/blob/8cc36ee10f84b82d0742ffcab770815c7d3f9ad7/router.go#L100) newUrl.String() is called which results in double encoded characters.

**Comment by dimfeld** [comment]
Thanks for the analysis! I'll see if I can spend some time fixing it this week, or I'm glad to take a PR as well.
