### ISSUE TITLE
Update Support for Go Modules

### ISSUE THREAD

**Issue by ardan-bkennedy** [dimfeld/httptreemux#68]
Hi, I have been using this package for possibily 5 years. With the new module system, it would be nice to update the module support.

There is a sticky point in that the current tag is v5.0.2. If you agree to this I would recommend tagging the project to v6.0.0 and have people use `https://github.com/dimfeld/httptreemux/v6` on the import paths to be compliant.

What do you think? I can do this.

**Comment by ardan-bkennedy** [comment]
As a side note. MVS is selecting version `5.0.1` for everyone because that version does not have a mod file. This means it is still compliant with your tag and the use of the `github.com/dimfeld/httptreemux` import.

I could go ahead and change my import to `github.com/dimfeld/httptreemux/v5` and MVS should select `v5.0.2` (which I will try).

**Comment by dimfeld** [comment]
Hi Bill, I see you closed the issue, so is there anything you'd still like me to do here? I haven't been keeping up to date on the details around Go modules, but I'm glad to obllige if there's some change that will make it a better experience.

**Comment by ardan-bkennedy** [comment]
I realized what you did with version 5.0.2 was fine. You could add documentation to tell people to import as `githhb.com/dimfeld/httptreemux/v5`. That is important.

**Comment by dimfeld** [comment]
Good idea, just added a note about that. Thanks!
