### ISSUE TITLE
How to serve static files

### ISSUE THREAD

**Issue by ghost** [dimfeld/httptreemux#78]
In defaultMux, I can serve static files like this.
```go
http.Handle("/files", http.FileServer(Http.Dir(uploadPath)))
```
In group.go, I haven't find something similar.
```go
TreeMux.Handler(path string, root http.FileSystem)  // not work
```

**Comment by dimfeld** [comment]
How are you creating the router? Have you tried using `NewContextMux`?

**Comment by yuanlai** [comment]
I tried to serve static files in [ardanlabs/service](https://github.com/ardanlabs/service/blob/10fb72f3de14fd3d842290c13a979726ee58e1bf/internal/platform/web/web.go#L46) and learning how to [wrap another Handle](https://github.com/ardanlabs/service/blob/10fb72f3de14fd3d842290c13a979726ee58e1bf/internal/platform/web/web.go#L102) to support it

**Comment by dimfeld** [comment]
Ok off the top of my head I guess you would need to do something like this: 

```go
contextMux = app.TreeMux.UsingContext()
contextMux.GET("/files/*", http.FileServer(Http.Dir(uploadPath)))
```

**Comment by pedia** [comment]
url :`/files/index.html` and `/files/` not handled.

/files/ 404

/files/index.html redirected by `fs`.

How can we handle `/files/`?

```
contextMux = app.TreeMux.UsingContext()
contextMux.GET("/files/*", http.FileServer(Http.Dir(uploadPath)))
```
