### ISSUE TITLE
Add handler templates for params

### ISSUE THREAD

**Issue by Kami-no** [dimfeld/httptreemux#80]
Please add the value of the handler template in params.

In case `router.GET("/:year/:month/:post", postHandler)` it would be nice to have smth like `params["template"]=="/:year/:month/:post"`

I've the same function for multiple different URL. I need to identify which URL template has triggered the function.

**Comment by dimfeld** [comment]
I'd prefer to not overload `params` to have contain multiple types of data, and this could possibly break someone's existing code if they iterate over the entire params map. 

But you can do this with the [context-based router](https://github.com/dimfeld/httptreemux#new-router-with-context-support) handlers, and use the `ContextData` or `ContextRoute` functions to get the original route template used.

**Comment by Kami-no** [comment]
OK, thank you.
